### ISSUE TITLE
[609541]  - Crtl+B | Anya | pacissiṭhaṅaca | पचिस्सिठङच | अञ्‍ञ/ब्याकरण गन्थ-सङ्गहो/मोग्गल्‍लानब्याकरणं

### ISSUE THREAD

**Issue by khanna-vijay** [VipassanaTech/tipitaka-xml#1385]
**Original Ticket Details:**

*   **OS Ticket Number:** 609541
*   **OS Ticket ID :** 2222
*   **Original OS Ticket URL:** https://ticket.vridhamma.org/scp/tickets.php?id=2222
*   **Status:** Open
*   **Department:** Tipitaka
*   **Created By:** Brihas Sarathy 
*   **Created Date:** 2020-10-12 16:35:06
*   **Last Updated Date:** 2020-10-12 16:35:07
*   **Original Assignee:** archana
*   **Last Message By:** Brihas Sarathy
*   *Overdue:* 0 | *Answered:* 0 | *Reopened:* N/A | *Closed:* N/A
*   *Message Created:* 2020-10-12 16:35:06 | *Message Updated:* N/A

---

**------------------------------------------------------**

**Message Body Original:**

<br>:star:**Message Posted by:** Brihas Sarathy on 2020-10-12 16:35:06
Crtl+ B Anya | Error Location | Error in Romn | Error in Deva | <br><br>Corrected text | Error checking source | XML Update Status<br><br><br><br>Location: Anya<br><br><br><br>Roman error: pacissiṭhaṅaca<br><br><br><br>Deva error: पचिस्सिठङच<br><br><br><br>Correction:<br><br><br><br>Basis for correction: Compared against original Burmese books<br><br><br><br>Status: Pending

---
**Attached Images:**
* **Master:** 609541_2222-ost-master.jpg
    • Image URLs:   → https://tipitaka.org/osticket/609541_2222-ost-master.jpg

**Comment by smeetpatel31** [comment]
the issue is fixed, by some other PRs.

**Comment by Archana-Deshpande** [comment]
@smeetpatel31 i can still see it as one word - पचिस्सिठङच instead of पचिस्सिठङ् च.
Please pay attention to the halant too, i.e. half letter ङ् which is not correctly spelt in पचिस्सिठङच

**Comment by smeetpatel31** [comment]
> [@smeetpatel31](https://github.com/smeetpatel31) i can still see it as one word - पचिस्सिठङच instead of पचिस्सिठङ् च. Please pay attention to the halant too, i.e. half letter ङ् which is not correctly spelt in पचिस्सिठङच

In the main branch, it is being corrected.
